---
ID: "b3124024-1e6e-4c80-821c-63a0d154b715"
Parent: "ff358c51-3c6a-49ac-b15f-81c74364ba26"
Template: "455a3e98-a627-4b40-8035-e683a0331ac7"
Path: /sitecore/templates/User Defined/Product Item/Product Section/Product Name
DB: master
SharedFields:
- ID: "ab162cc0-dc80-4abf-8871-998ee5d7ba32"
  Hint: Type
  Value: "Single-Line Text"
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 100
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180412T122014Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
